---

- name: calculate user
  set_fact:
    user_conf: "{{ mariadb_default_user_conf | combine(user) }}"

- name: Manage Mariadb users to create
  mysql_user:
    name: "{{ user_conf.name }}"
    host: "{{ item }}"
    password: "{{ user_conf.password }}"
    priv: "{{ user_conf.privs | join('/')  }}"
    state: present
    append_privs: "{{ user_conf.append_privs }}"
  no_log: true
  loop: "{{ user_conf.hosts }}"
...
